blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name="home"),
    path('search/<str:query>/', views.search, name="search"),
    path('category/<str:query>/', views.category, name="category"),
    path('post_detail/<int:id>/', views.post_detail, name='post_detail' ),
    path('post_create/', views.post_create, name='post_create'),
    path('post_update/<int:id>/', views.post_update, name='post_update'),
    path('post_delete/<int:id>/', views.post_delete, name='post_delete'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from user.api import UserListCreate
from blog.api import PostViewSet, CategoryViewSet

router = routers.DefaultRouter()
router.register(r'users', UserListCreate)
router.register(r'posts', PostViewSet)  
router.register(r'categories', CategoryViewSet)  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('registrations/sign-up/', views.sign_up, name="sign_up"),
    path('registrations/ign-in/', views.LoginView.as_view(), name="sign_in"),
    path("dashboard/<uuid:id>/", views.dashboard, name="dashboard"),
    path("profile/<uuid:id>/", views.profile, name="profile"),
    path("follow/<uuid:id>/", views.follow, name="follow"),
    path("followers/<uuid:id>/", views.follow_info, name="follow_info"),
    path('logout/', views.user_logout, name='user_logout'),
]

templates/regitration/signin.html
{% extends 'regitration/base_regitration.html' %} 
{% block content %}
<section>
	<div class="container">
		<div class="row">
      <div class="col-md-10 col-lg-8 col-xl-6 mx-auto">
        <div class="p-4 p-sm-5 bg-primary bg-opacity-10 rounded">
					<h2>Hisobingizga kiring</h2>
					<!-- Form START -->
					<form method="post" class="mt-4">
						
						{% csrf_token %}
						{{ form }}

						<div class="row align-items-center">
							<div class="col-sm-4">
								<button type="submit" class="btn btn-success">Jo'natish</button>
							</div>
							<div class="col-sm-8 text-sm-end">
								<span>Akkountingiz mavjud emasmi?<a href="{% url 'user:sign_up' %}"><u>Ro'yxatdan o'tish</u></a></span>
							</div>
						</div>
					</form>
					<!-- Form END -->
					<hr>
					<!-- Social-media btn -->
					<div class="text-center">
						<p>Sign in with your social network for quick access</p>
						<ul class="list-unstyled d-sm-flex mt-3 justify-content-center">
							<li class="mx-2">
								<a href="#" class="btn bg-facebook d-inline-block"><i class="fab fa-facebook-f me-2"></i> Sign in with Facebook</a>
							</li>
							<li class="mx-2">
								<a href="#" class="btn bg-google d-inline-block"><i class="fab fa-google me-2"></i> Sign in with google</a>
							</li>
						</ul>
					</div>
        </div>
      </div>
    </div>
	</div>
</section>
{% endblock %}

templates/regitration/signup.html
{% extends 'regitration/base_regitration.html' %} 

{% block content %}
<section>
	<div class="container">
		<div class="row">
      <div class="col-md-10 col-lg-8 col-xl-6 mx-auto">
        <div class="p-4 p-sm-5 bg-primary bg-opacity-10 rounded">
					<h2>Shaxsiy hisob yarating</h2>
					<!-- Form START -->
					<form method="post" action="">
						{% csrf_token %}
						{{ form }}

						<div class="row align-items-center">
							<div class="col-sm-4">
								<button type="submit" class="btn btn-success">Jo'natish</button>
							</div>
							<div class="col-sm-8 text-sm-end">
								<span>Akkountingiz mavjudmi?<a href="{% url 'user:sign_in' %}"><u>Kirish</u></a></span>
							</div>
						</div>
					</form>
					<!-- Form END -->
					<hr>
					<!-- Social-media btn -->
					<div class="text-center">
						<p>Sign in with your social network for quick access</p>
						<ul class="list-unstyled d-sm-flex mt-3 justify-content-center">
							<li class="mx-2">
								<a href="#" class="btn bg-facebook d-inline-block"><i class="fab fa-facebook-f me-2"></i> Sign in with Facebook</a>
							</li>
							<li class="mx-2">
								<a href="#" class="btn bg-google d-inline-block"><i class="fab fa-google me-2"></i> Sign in with google</a>
							</li>
						</ul>
					</div>
        </div>
      </div>
    </div>
	</div>
</section>
{% endblock %}