blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name="home"),
    path('search/<str:query>/', views.search, name="search"),
    path('category/<str:query>/', views.category, name="category"),
    path('post_detail/<int:id>/', views.post_detail, name='post_detail' ),
    path('post_create/', views.post_create, name='post_create'),
    path('post_update/<int:id>/', views.post_update, name='post_update'),
    path('post_delete/<int:id>/', views.post_delete, name='post_delete'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from user.api import UserListCreate
from blog.api import PostViewSet, CategoryViewSet

router = routers.DefaultRouter()
router.register(r'users', UserListCreate)
router.register(r'posts', PostViewSet)  
router.register(r'categories', CategoryViewSet)  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('registrations/sign-up/', views.sign_up, name="sign_up"),
    path('registrations/ign-in/', views.LoginView.as_view(), name="sign_in"),
    path("dashboard/<uuid:id>/", views.dashboard, name="dashboard"),
    path("profile/<uuid:id>/", views.profile, name="profile"),
    path("follow/<uuid:id>/", views.follow, name="follow"),
    path("followers/<uuid:id>/", views.follow_info, name="follow_info"),
    path('logout/', views.user_logout, name='user_logout'),
]

templates/category.html
{% extends 'base.html' %} 

{% block content %}


    <section class="pt-4">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <!-- Title -->
            <div class="mb-4 d-md-flex justify-content-between align-items-center" >
              <h2 class="m-0">
                <i class="bi bi-megaphone"></i> 
                {{ query }} Category Posts
              </h2>
            </div>
            <div class="tiny-slider arrow-hover arrow-blur arrow-dark arrow-round" >
              <div class="tiny-slider-inner" data-autoplay="true" data-hoverpause="true" data-gutter="24" data-arrow="true" data-dots="false" data-items-xl="4" data-items-md="3" data-items-sm="2" data-items-xs="1">

                {% for post in posts %}
                <!-- Card item START -->
                <div class="card">
                  <!-- Card img -->
                  <div class="position-relative">
                    {% if post.img %}
                    <img class="card-img" src="{{ post.img.url }}" alt="Card image">
                    {% endif %}
                    <div class="card-img-overlay d-flex align-items-start flex-column p-3">

                      {% if post.video %}
                      <!-- vidoe -->
                      <div class="w-100 mb-auto d-flex justify-content-end">
                        <div class="text-end ms-auto">
                          <!-- Card format icon -->
                          <div class="icon-md bg-white bg-opacity-25 bg-blur text-primary rounded-circle" title="This post has video">
                            <i class="fas fa-video"></i>
                          </div>
                        </div>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="card-body px-0 pt-3">
                    <a href="#!" class="mb-0 text-body small" tabindex="0" role="button" data-bs-container="body" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-placement="top" data-bs-content="You're seeing this ad because your activity meets the intended audience of our site.">
                      <i class="bi bi-info-circle ps-1"></i>{{ post.category }}
                    </a>
                    <h5 class="card-title">
                      <a href="{% url 'blog:post_detail' post.id %}" class="btn-link text-reset fw-bold">
                        {{ post.name }}
                      </a>
                    </h5>
                    <p class="card-text">
                      {{ post.summary }}
                    </p>
                    <!-- Card info -->
                    <ul class="nav nav-divider align-items-center d-none d-sm-inline-block">
                      <li class="nav-item">
                        <div class="nav-link">
                          <div class="d-flex align-items-center position-relative">
                            <div class="avatar avatar-xs">
                              <div class="avatar-img rounded-circle bg-success">
                                <span class="text-white position-absolute top-50 start-50 translate-middle fw-bold small">
                                  {{ post.author.full_name|slice:":1" }}
                                </span>
                              </div>
                            </div>
                            <span class="ms-3">by 
                              <a href="#" class="stretched-link text-reset btn-link">
                                {{ post.author.full_name|truncatewords:1 }}
                              </a>
                            </span>
                          </div>
                        </div>
                      </li>
                      <li class="nav-item">{{ post.created_at|date:"Y-m-d" }}</li>
                    </ul>
                  </div>
                </div>
                <!-- Card item END -->
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %} 
{% block content %}

<section class="py-4">
  <div class="container">
    <div class="row g-4">
      <div class="col-12">
        <!-- Counter START -->
        <div class="row g-4">
          <!-- Counter item -->
          <div class="col-sm-6 col-lg-3">
            <div class="card card-body border p-3">
              <div class="d-flex align-items-center">
                <!-- Icon -->
                <div
                  class="icon-xl fs-1 bg-success bg-opacity-10 rounded-3 text-success"
                >
                  <i class="bi bi-people-fill"></i>
                </div>
                <!-- Content -->
                <div class="ms-3">
                  <h3>134K</h3>
                  <h6 class="mb-0">Pageviews</h6>
                </div>
              </div>
            </div>
          </div>

          <!-- Counter item -->
          <div class="col-sm-6 col-lg-3">
            <div class="card card-body border p-3">
              <div class="d-flex align-items-center">
                <!-- Icon -->
                <div
                  class="icon-xl fs-1 bg-primary bg-opacity-10 rounded-3 text-primary"
                >
                  <i class="bi bi-file-earmark-text-fill"></i>
                </div>
                <!-- Content -->
                <div class="ms-3">
                  <h3>{{ posts_count }}</h3>
                  <h6 class="mb-0">Posts</h6>
                </div>
              </div>
            </div>
          </div>

          <!-- Counter item -->
          <div class="col-sm-6 col-lg-3">
            <div class="card card-body border p-3">
              <div class="d-flex align-items-center">
                <!-- Icon -->
                <div
                  class="icon-xl fs-1 bg-danger bg-opacity-10 rounded-3 text-danger"
                >
                  <i class="bi bi-suit-heart-fill"></i>
                </div>
                <!-- Content -->
                <div class="ms-3">
                  <h3>2150</h3>
                  <h6 class="mb-0">Likes</h6>
                </div>
              </div>
            </div>
          </div>

          <!-- Counter item -->
          <div class="col-sm-6 col-lg-3">
            <div class="card card-body border p-3">
              <div class="d-flex align-items-center">
                <!-- Icon -->
                <div
                  class="icon-xl fs-1 bg-info bg-opacity-10 rounded-3 text-info"
                >
                  <i class="bi bi-bar-chart-line-fill"></i>
                </div>
                <!-- Content -->
                <div class="ms-3">
                  <h3>84K</h3>
                  <h6 class="mb-0">Visitors</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Counter END -->
      </div>


      <div class="col-12">
        <!-- Blog list table START -->
        <div class="card border bg-transparent rounded-3">
          <!-- Card header START -->
          <div class="card-header bg-transparent border-bottom p-3">
            <div class="d-sm-flex justify-content-between align-items-center">
              <h5 class="mb-2 mb-sm-0">
                Blog list
                <span class="badge bg-primary bg-opacity-10 text-primary">
                  {{ posts_count }}
                </span>
              </h5>
              <a href="{% url 'blog:post_create' %}" class="btn btn-sm btn-primary mb-0">
                Add New
              </a>
            </div>
          </div>
          
          <div class="card-body">
            
            <div class="row g-3 align-items-center justify-content-between mb-3">
              
              <div class="col-md-8">
                <form class="rounded position-relative">
                  <input class="form-control pe-5 bg-transparent" type="search" placeholder="Search" aria-label="Search"/>
                  <button class="btn bg-transparent border-0 px-2 py-0 position-absolute top-50 end-0 translate-middle-y" type="submit" >
                    <i class="fas fa-search fs-6"></i>
                  </button>
                </form>
              </div>

              <div class="col-md-3">
                <!-- Short by filter -->
                <form>
                  <select
                    class="form-select z-index-9 bg-transparent"
                    aria-label=".form-select-sm">

                    <option value="">Sort by</option>
                    <option>Free</option>
                    <option>Newest</option>
                    <option>Oldest</option>
                  </select>
                </form>
              </div>
            </div>
            <!-- Search and select END -->

            <!-- Blog list table START -->
            <div class="table-responsive border-0">
              <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                <!-- Table head -->
                <thead class="table-dark">

                  <tr>
                    <th scope="col" class="border-0 rounded-start">
                      Blog Name
                    </th>
                    <th scope="col" class="border-0">Published Date</th>
                    <th scope="col" class="border-0">Categories</th>
                    <th scope="col" class="border-0 rounded-end">Action</th>
                  </tr>

                </thead>

                <!-- Table body START -->
                <tbody class="border-top-0">
                  {% for post in posts %}
                  <tr>
                    <!-- Table data -->
                    <td>
                      <h6 class="course-title mt-2 mt-md-0 mb-0">
                        <a href="#">
                          {{ post.name|truncatewords:8 }}
                        </a>
                      </h6>
                    </td>
                    <!-- Table data -->
                    <td>{{ post.created_at|timesince }}</td>
                    <!-- Table data -->
                    <td>
                      <a href="#" class="badge text-bg-warning mb-2">
                        <i class="fas fa-circle me-2 small fw-bold"></i>
                        {{ post.category }}
                      </a>
                    </td>
                    <!-- Table data -->
                    <td>
                      <div class="d-flex gap-2">
                        <a
                          href="{% url 'blog:post_delete' post.id %}"
                          class="btn btn-light btn-round mb-0"
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          aria-label="Delete"
                          data-bs-original-title="Delete">
                          <i class="bi bi-trash"></i>
                        </a>
                        <a
                          href="{% url 'blog:post_update' post.id %}"
                          class="btn btn-light btn-round mb-0"
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          aria-label="Edit"
                          data-bs-original-title="Edit">
                          <i class="bi bi-pencil-square"></i>
                        </a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}


                </tbody>
                <!-- Table body END -->
              </table>
            </div>
            <!-- Blog list table END -->

            {% if posts.has_other_pages %}
            <div class="d-sm-flex justify-content-sm-between align-items-sm-center mt-4 mt-sm-3">
              <!-- Content -->
              <p class="mb-sm-0 text-center text-sm-start">
                Showing 1 to 8 of 20 entries
              </p>
              <!-- Pagination -->
              <nav class="mb-sm-0 d-flex justify-content-center" aria-label="navigation">
                <ul class="pagination">

                  {% if posts.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page=1">Previous</a></li>
                  {% else %}
                  <li class="page-item disabled"></li>
                  {% endif %}

                  {% for i in posts.paginator.page_range %}
                  {% if posts.number == i %}
                  <li class="page-item disabled"><a class="page-link">{{ i }}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
                  {% endif %}
                  {% endfor %}

                </ul>
              </nav>
            </div>
            {% endif %}
          </div>
        </div>
        <!-- Blog list table END -->
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/follow_info.html
{% extends 'base.html' %} {% block content %}

<section class="py-4">
	<div class="container">
		<div class="row g-4">
			<div class="col-12">
				<!-- Card START -->
				<div class="card border">
					<!-- Card header START -->
					<div class="card-header border-bottom p-3">
						<h5 class="mb-2 mb-sm-0">Followers</h5>
					</div>
					<!-- Card header END -->

					<!-- Card body START -->
					<div class="card-body p-3">
						<!-- Table START -->
						<div class="table-responsive border-0">
							<table class="table align-middle p-4 mb-0 table-hover">
								<!-- Table head -->
								<thead class="table-dark">
									<tr>
										<th scope="col" class="border-0 rounded-start">First Last name</th>
										<th scope="col" class="border-0">Telephone</th>
										<th scope="col" class="border-0">Job</th>
									</tr>
								</thead>

								<tbody class="border-top-0">
									{% for follower in user.followers.all %}
									<tr>
										<td>
											<div class="d-flex align-items-center position-relative">
												<!-- Image -->
												<div class="avatar avatar-md">
													{% if follower.follower.avatar %}
													<img src="{{ follower.follower.avatar.url }}" class="rounded-circle"
														alt />
													{% else %}
													<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnEquqKx_4BB68GJN8C8aUfZu6wBaBeQeqMQ&usqp=CAU"
														class="rounded-circle" alt="" />
													{% endif %}
												</div>
												<div class="mb-0 ms-2">

													<h6 class="mb-0">
														<a href="{% url 'user:profile' follower.follower.id %}"
															class="stretched-link">
															{{ follower.follower.full_name}}
														</a>
													</h6>
												</div>
											</div>
										</td>

										<td>{{ follower.follower.phone }}</td>

										{% if follower.follower.job %}
										<td>{{ follower.follower.job }}</td>
										{% else %}
										<td>None</td>
										{% endif %}
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-12">
				<!-- Card START -->
				<div class="card border">
					<!-- Card header START -->
					<div class="card-header border-bottom p-3">
						<h5 class="mb-2 mb-sm-0">Followings</h5>
					</div>
					<!-- Card header END -->

					<!-- Card body START -->
					<div class="card-body p-3">
						<!-- Table START -->
						<div class="table-responsive border-0">
							<table class="table align-middle p-4 mb-0 table-hover">
								<!-- Table head -->
								<thead class="table-dark">
									<tr>
										<th scope="col" class="border-0 rounded-start">First Last name</th>
										<th scope="col" class="border-0">Telephone</th>
										<th scope="col" class="border-0">Job</th>
									</tr>
								</thead>

								
								<tbody class="border-top-0">
									{% for following in user.followings.all %}
									<tr>
										<td>
											<div class="d-flex align-items-center position-relative">
												<!-- Image -->
												<div class="avatar avatar-md">
													{% if following.user.avatar %}
													<img src="{{ following.user.avatar.url }}" class="rounded-circle" alt="" />
													{% else %}
													<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnEquqKx_4BB68GJN8C8aUfZu6wBaBeQeqMQ&usqp=CAU"
														class="rounded-circle" alt=""/>
													{% endif %}
												</div>
												<div class="mb-0 ms-2">

													<h6 class="mb-0">
														<a href="{% url 'user:profile' following.user.id %}"
															class="stretched-link">
															{{ following.user.full_name}}
														</a>
													</h6>
												</div>
											</div>
										</td>

										<td>{{ following.user.phone }}</td>	

										{% if user.job %}
										<td>{{ following.user.job }}</td>
										{% else %}
										<td>None</td>
										{% endif %}
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

templates/search.html
{% extends 'base.html' %} 

{% block content %}



    <section class="position-relative">
      <div class="container" data-sticky-container="">
        <div class="row">


          <div class="col-lg-9">
            <div class="mb-4">
              <h2 class="m-0"><i class="bi bi-hourglass-top me-2"></i>
                Search Results
              </h2>
            </div>
            <div class="row gy-4">
              {% for post in posts %}
              {% if not post.video %}
              <div class="col-sm-6">
                <div class="card">
                  <div class="position-relative">
                    {% if post.img %}
                    <img class="card-img" src="{{ post.img.url }}" alt="Card image">
                    {% endif %}

                    <div class="card-img-overlay d-flex align-items-start flex-column p-3">

                      {% if post.video %}
                      <div class="w-100 mb-auto d-flex justify-content-end">
                        <div class="text-end ms-auto">
                          <div class="icon-md bg-white bg-opacity-25 bg-blur text-primary rounded-circle" title="This post has video">
                            <i class="fas fa-video"></i>
                          </div>
                        </div>
                      </div>
                      {% endif %}
                      {% if post.audio %}
                      <div class="w-100 my-auto">
                        <div class="player-wrapper bg-light rounded">
                          <audio class="player-audio mb-4" crossorigin>
                            <source  src="{{ post.audio.url }}" type="audio/mp3">
                          </audio>
                        </div>
                      </div>
                      {% endif %}

                      {% if not post.video %}
                      <div class="w-100 mt-auto">
                        <a href="#" class="badge text-bg-primary mb-2">
                          <i class="fas fa-circle me-2 small fw-bold"></i>
                          {{ post.category }}
                        </a>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="card-body px-0 pt-3">
                    {% if post.status %}
                    <a href="#!" class="mb-0 text-body small" tabindex="0" role="button" data-bs-container="body" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-placement="top" data-bs-content="You're seeing this ad because your activity meets the intended audience of our site.">
                      <i class="bi bi-info-circle ps-1"></i> Sponsored
                    </a>
                    {% endif %}
                    <h4 class="card-title">
                      <a href="{% url 'blog:post_detail' post.id %}" class="btn-link text-reset fw-bold">
                        {{ post.name }}
                      </a>
                    </h4>
                    <p class="card-text">
                      {{ post.summary }}
                    </p>
                    <ul class="nav nav-divider align-items-center d-none d-sm-inline-block">
                      <li class="nav-item">
                        <div class="nav-link">
                          <div class="d-flex align-items-center position-relative">
                            <div class="avatar avatar-xs">
                              <div class="avatar-img rounded-circle bg-success">
                                {% if post.author.avatar %}
                                  <img class="avatar-img rounded-circle border border-white border-3 shadow" src="{{ post.author.avatar.url }}">
                                {% else %}
                                  <span class="text-white position-absolute top-50 start-50 translate-middle fw-bold small">
                                    {{ post.author.full_name|slice:":1" }}
                                  </span>
                                {% endif %}
                                
                              </div>
                            </div>
                            <span class="ms-3">by 
                              <a href="{% url 'user:profile' post.author.id %}" class="stretched-link text-reset btn-link">
                                {{ post.author.full_name|truncatewords:1 }}
                              </a>
                            </span>
                          </div>
                        </div>
                      </li>
                      <li class="nav-item">{{ post.created_at|date:"Y-m-d" }}</li>
                    </ul>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}


              <div class="col-12 text-center mt-5">
                <button type="button" class="btn btn-primary-soft">Load more post <i class="bi bi-arrow-down-circle ms-2 align-middle"></i></button>
              </div>
            </div>
          </div>


        </div> 
      </div>
    </section>

    

    

{% endblock %}